# Generated by Django 3.1.8 on 2021-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('school', models.CharField(max_length=99)),
                ('college', models.CharField(max_length=99)),
                ('university', models.CharField(max_length=99)),
                ('cgpa', models.CharField(max_length=99)),
                ('skill', models.CharField(max_length=99)),
            ],
        ),
    ]
