# Generated by Django 3.1.8 on 2021-10-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211028_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('school', models.CharField(max_length=1000)),
                ('college', models.CharField(max_length=1000)),
                ('university', models.CharField(max_length=1000)),
                ('cgpa', models.CharField(max_length=1000)),
                ('skill', models.CharField(max_length=1000)),
            ],
        ),
    ]
