# Generated by Django 3.1.8 on 2021-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211028_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='jobs',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='username',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
