# Generated by Django 3.1.8 on 2021-11-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
