# Generated by Django 3.1.8 on 2021-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
