# Generated by Django 3.1.8 on 2021-11-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211115_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_profile_model',
            name='cv',
        ),
    ]
