# Generated by Django 3.1.8 on 2021-11-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_edit_profile_model_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_profile_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
            ],
        ),
        migrations.RemoveField(
            model_name='edit_profile_model',
            name='profile_picture',
        ),
    ]
