# Generated by Django 3.1.8 on 2021-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_cv',
            name='address',
        ),
        migrations.RemoveField(
            model_name='all_cv',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='all_cv',
            name='email',
        ),
        migrations.RemoveField(
            model_name='all_cv',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='all_cv',
            name='university',
        ),
        migrations.AddField(
            model_name='all_cv',
            name='cv',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
    ]
