# Generated by Django 3.1.8 on 2022-01-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211119_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_for_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('post_id', models.CharField(max_length=1000)),
                ('job_title', models.CharField(max_length=1000, null=True)),
                ('phone', models.CharField(max_length=1000, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('education', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
