# Generated by Django 3.1.8 on 2022-01-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_apply_for_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_for_job',
            old_name='job_title',
            new_name='title',
        ),
    ]
