# Generated by Django 3.1.8 on 2022-01-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20220112_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
